"""empty message

Revision ID: 3e2d851200b4
Revises: 2e9123e3bffa
Create Date: 2019-12-19 20:39:20.729356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2d851200b4'
down_revision = '2e9123e3bffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('word', sa.String(), nullable=True))
    op.drop_column('words', 'wt3')
    op.drop_column('words', 'wt1')
    op.drop_column('words', 'wt2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('wt2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('wt1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('wt3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('words', 'word')
    # ### end Alembic commands ###
