"""empty message

Revision ID: 7ad6f4fcc274
Revises: f29b9de0d4e1
Create Date: 2019-12-19 23:54:54.312609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad6f4fcc274'
down_revision = 'f29b9de0d4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('p1', sa.String(), nullable=True),
    sa.Column('p2', sa.String(), nullable=True),
    sa.Column('p3', sa.String(), nullable=True),
    sa.Column('p4', sa.String(), nullable=True),
    sa.Column('p5', sa.String(), nullable=True),
    sa.Column('p6', sa.String(), nullable=True),
    sa.Column('p7', sa.String(), nullable=True),
    sa.Column('p8', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
